name: Notification

on:
  push:
    paths:
      - ".github/workflows/**"
      - "src/index.js"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          status: success
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

      - uses: ./
        with:
          status: cancelled 
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
        
      - uses: ./
        with:
          status: failure
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
      
